import{S as u}from"./assets/vendor-3a49940e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const f="42569915-bcd29008899db620988a57306",p="https://pixabay.com/api/",l=document.querySelector(".loader");function d(o){const e=new URLSearchParams({key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return l.style.display="block",fetch(`${p}?${e}`).then(r=>{if(!r.ok)throw new Error("Network response was not OK!");return r.json()}).then(r=>(l.style.display="none",r.hits.length===0&&iziToast.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),r)).catch(r=>console.error("Error fetching data:",r))}function g(o){return o.hits.map(e=>`<div class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="gallery-image-info">
            <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
            <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
            <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
            <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
        </div>
    </div>`).join("")}const h=new u(".gallery-link",{captionsData:"alt",captionDelay:250}),m=document.querySelector("#searchForm"),i=document.querySelector(".gallery");let n="";m.addEventListener("submit",y);function y(o){if(o.preventDefault(),i.innerHTML="",n=m.elements.searchQuery.value.trim(),n===""){alert("Enter your request"),i.innerHTML="";return}d(n).then(e=>{const r=g(e);i.insertAdjacentHTML("beforeend",r),h.refresh()}).catch(e=>console.error("Error fetching data:",e))}
//# sourceMappingURL=commonHelpers.js.map
