import{S as u,i as f}from"./assets/vendor-7659544d.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const p="42569915-bcd29008899db620988a57306",d="https://pixabay.com/api/",l=document.querySelector(".loader");function g(s){const e=new URLSearchParams({key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return l.style.display="block",fetch(`${d}?${e}`).then(r=>{if(!r.ok)throw new Error("Network response was not OK!");return r.json()}).then(r=>(l.style.display="none",r.hits.length===0&&iziToast.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),r)).catch(r=>console.error("Error fetching data:",r))}function h(s){return s.hits.map(e=>`<div class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="gallery-image-info">
            <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
            <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
            <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
            <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
        </div>
    </div>`).join("")}const y=new u(".gallery-link",{captionsData:"alt",captionDelay:250}),m=document.querySelector("#searchForm"),a=document.querySelector(".gallery");let n="";m.addEventListener("submit",b);function b(s){if(s.preventDefault(),a.innerHTML="",n=m.elements.searchQuery.value.trim(),n===""){f.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Enter your request"}),a.innerHTML="";return}g(n).then(e=>{const r=h(e);a.insertAdjacentHTML("beforeend",r),y.refresh()}).catch(e=>console.error("Error fetching data:",e))}
//# sourceMappingURL=commonHelpers.js.map
